# Generated by Django 4.2.24 on 2025-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "favourites",
            },
        ),
        migrations.CreateModel(
            name="ModelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model_category",
            },
        ),
        migrations.CreateModel(
            name="XLoveCashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "xlovecash_tags",
            },
        ),
        migrations.CreateModel(
            name="WebcamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                (
                    "unique_user_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("is_online", models.BooleanField(default=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=40, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.CharField(max_length=255)),
                ("iframe", models.TextField(blank=True, null=True)),
                ("link_embed", models.TextField(blank=True, null=True)),
                ("link_snapshot", models.TextField(blank=True, null=True)),
                ("url_stream", models.TextField(blank=True, null=True)),
                ("chat_url", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=12)),
                ("json_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="models",
                        through="models_app.ModelCategory",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "db_table": "models",
            },
        ),
    ]
