# Generated by Django 4.2.24 on 2025-10-01 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcammodel",
            name="favourited_by",
            field=models.ManyToManyField(
                related_name="favourited_models",
                through="models_app.Favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
        migrations.AddField(
            model_name="modelcategory",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models_app.webcammodel"
            ),
        ),
        migrations.AddField(
            model_name="favourite",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models_app.webcammodel"
            ),
        ),
        migrations.AddField(
            model_name="favourite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="webcammodel",
            index=models.Index(fields=["model_id"], name="models_model_i_ed7318_idx"),
        ),
        migrations.AddIndex(
            model_name="webcammodel",
            index=models.Index(fields=["user_name"], name="models_user_na_6e9c6e_idx"),
        ),
        migrations.AddIndex(
            model_name="webcammodel",
            index=models.Index(fields=["gender"], name="models_gender_2bbdb2_idx"),
        ),
        migrations.AddIndex(
            model_name="webcammodel",
            index=models.Index(fields=["source"], name="models_source_9ef66e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="modelcategory",
            unique_together={("model", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("model", "user")},
        ),
    ]
