# Generated by Django 4.2.24 on 2025-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0003_notification_subscription_webcammodel_is_naked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcammodel",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webcammodel",
            name="last_tweeted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webcammodel",
            name="tweet_count",
            field=models.IntegerField(default=0),
        ),
    ]
